name: "tiktok"
mode: "debug"
port: 8081
version: "v0.0.2"
start_time: "2022-05-10"
machine_id: 1

mysql:
    host: "127.0.0.1:3306"
    user: ""
    password: ""
    db_name: "tiktoklite"

redis:
    host: "127.0.0.1:6379"
    password: ""
    db: 0


publish:
    #publish mode, true : qi niu cloud ; false : local storage (Enter the external IP address of the local host)
    mode: false
    #access url prefix
    qi_niu_cloud_play_url_prefix: ""
    qi_niu_cloud_cover_url_prefix: ""
    #Enter the external IP address of the local host
    local_ip_address: ""
    #local storage path prefix
    video_path_prefix: "./public/videos/"
    cover_path_prefix: "./public/covers/"
    #qiniucloud api key
    access_key: ""
    secret_key: ""
    #qiniucloud buket name
    bucket_name: "tiktoklite-feed"
